"""add tag to case

Revision ID: 10067dec1aae
Revises: 9436c3b1cef5
Create Date: 2026-03-06 18:20:02.122403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10067dec1aae'
down_revision = '9436c3b1cef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
